### PR TITLE
Fix OSS Notices to include SPDX (json) and SPDX (yaml)

### LINKED ISSUE #215: Among OSS Notices, SPDX (json), SPDX (yaml) are not included in OSS Notice.
**Describe the bug**
Among OSS Notices, SPDX (json), SPDX (yaml) are not included in OSS Notice. 

**To Reproduce**
1. Packaging - Notice Tab > Click SPDX (json), SPDX (yaml) > Confirm.
image

2. Click OSS Notice icon in Project List's download column.
image

3. Unzip downloaded file.
image
-> SPDX (json), SPDX (yaml) are missing. 

**Expected behavior**
The OSS Notice file in the compressed file should be created according to the OSS Notice file format checked in the Notice tab.

### PR DESCRIPTION
**Pull request by riyenas0925**
## Description
Fix OSS Notices to include SPDX (json) and SPDX (yaml)

1. Packaging - Notice Tab > Click SPDX (SpreadSheet), Click SPDX (TAG), Click SPDX (json), SPDX (yaml) > Confirm.
image

2. Unzip downloaded file.
image

Resolves #215

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

File: src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java [hunk 1]
```diff
@@ -1163,7 +1164,8 @@ public void updateStatusWithConfirm(Project project, OssNotice ossNotice) throws
 		// SPDX
 		String spdxSheetFileId = null;
 		if(CoConstDef.FLAG_YES.equals(project.getAllowDownloadSPDXSheetYn())) {
-			spdxSheetFileId = ExcelDownLoadUtil.getExcelDownloadId("spdx", project.getPrjId(), EXPORT_TEMPLATE_PATH);
+			String dataStr = Maps.immutableEntry("prjId", project.getPrjId()).toString();
```
Comment (riyenas0925) [inline src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java:1167]: If it is changed to JAVA 11 later, it will be changed to the method below.
```java
String dataStr = Map.of("prjId", project.getPrjId()).toString();
```

File: src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java [hunk 2]
```diff
@@ -1180,7 +1184,9 @@ public void updateStatusWithConfirm(Project project, OssNotice ossNotice) throws
 		
 		if(CoConstDef.FLAG_YES.equals(project.getAllowDownloadSPDXRdfYn())) {
 			if(isEmpty(spdxSheetFileId)) {
-				spdxSheetFileId = ExcelDownLoadUtil.getExcelDownloadId("spdx", project.getPrjId(), EXPORT_TEMPLATE_PATH);
+				Map<String, String> data = new HashMap<>(); data.put("prjId", project.getPrjId());
```
Comment (riyenas0925) [inline src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java:1187]: If it is changed to JAVA 11 later, it will be changed to the method below.

``` java
Map<String, String> data = Map.of("prjId", project.getPrjId());
```
